### PR TITLE
Support Vivaldi, Opera, Brave and IE

### PR DESCRIPTION
**Pull request by Venom-Code**
Added Support for Vivaldi, Opera, Brave and Internet Explorer

### CODE REVIEW

**Comment by brapifra** [comment]
I don't know vivaldi, opera and brave but... Are you sure that Internet Explorer will be launched with start ie http:localhost:[port]?

**Comment by brapifra** [comment]
Have u checked all/some of this works?

**Comment by Venom-Code** [comment]
Work fine for me, in all of these browsers.

**Comment by brapifra** [comment]
You have lied to me, it's no working anything, and you haven't tested it. I was a little bit naive merging it so quickly. I know where is the problem in your code, but I'm not going to tell you that, try to be more honest next time.

**Pull request merged**
