### PR TITLE
More Specific Shortcut Menu & Fix implementation issue for Browser & settings

### PR DESCRIPTION
**Pull request by ritwickdey**
It is really annoy that the shortcut "Serve Project with PHP " & "Stop PHP Server" is for all file. 
I mean, when I am working on C# or Java or HTML or anything else except PHP, the option should disappear. Here is the fix.

### CODE REVIEW

**Comment by ritwickdey** [comment]
More fix ->> 

1. Browser is not opening from 2nd time of starting server. *(As the code for calling of browser is not defined under the anonymous function)*

2. None of the setting is not updating after changing of values. *(As all settings are defined in global scope & marked as 'const' value, that should not be. Because settings is changeable)*

**Comment by brapifra** [comment]
Thanks for your PR!
However, I think that shortcuts for context menu should always be available. It's possible that someone wants to try to serve some file different than .php (.html, .js, plain text, images...). This extension is a good tool to achieve that. Don't you think?
About the browser, I did it that way because I think that most of developers don't want that their browser opens each time they start the server. I personally prefer to keep the browser opened after the first start. Nevertheless, create a setting to configure this behavior could be a good option.
Let me know what you think! Awesome contribution!

**Comment by ritwickdey** [comment]
I totally agree with you! But that should be a different extension or naming convention.  

Suppose, I want to open HTML file through server, that should  be  "open with server", not "open with PHP Server" .  Do you not think it is unconventional?

**Comment by ritwickdey** [comment]
...And It is okay for .php, .html, .htm....

But what about other files, .c, .cs, .java, .py ..............

**Comment by brapifra** [comment]
Yes, it may be a bit unconventional but you are actually opening the file with a PHP server. I think I will keep it that way for now.
Anyway, thank you again for your PR! I'm going to fix the settings issue!

**Comment by ritwickdey** [comment]
Okay. Thank You 😄

**Comment by brapifra** [comment]
Thank YOU!

**Pull request closed without merging**
