### PR TITLE
I think you have some error!?

### PR DESCRIPTION
**Pull request by deeyi2000**
fix: phpPath has no effect and filename lost a character.

### CODE REVIEW

**Comment by brapifra** [comment]
I am not able to reproduce the use case where filename loses a character! Can you give me an example?
Thanks for the PR

**Comment by deeyi2000** [comment]
when I set "phpserver.relativePath": ".\\public" the filename will lose a character.
because of it's started with .(dot).
but when I remove .(dot) php can't start.
image

**Comment by deeyi2000** [comment]
image

**Comment by brapifra** [comment]
Thank you for the quick reply! I think I've fixed the problem with the 2.4.3 version.
Let me know what you think!

**Comment by FatehDzIt** [comment]
Hi friend your extn works well but i have a issue it works only for the first folder in workspace.... For other folders i got "404 not found" and missing characters how to fix it plz

**Pull request closed without merging**
